schemaVersion: 2.2.0
metadata:
  name: scroll
projects:
  - clonePath: scroll
    git:
      remotes:
        origin: https://github.com/ludovicus3/scroll.git
    name: scroll
components:
  - name: redis
    container:
      endpoints:
        - exposure: none
          name: redis
          targetPort: 6379
      image: redis:{{redisTag}}
      command:
        - redis-server
      args:
        - '--appendonly'
        - 'yes'
      volumeMounts:
        - name: cache
          path: /data
  - name: postgres
    container:
      endpoints:
        - exposure: none
          name: postgresql
          targetPort: 5432
      env:
        - name: POSTGRES_USER
          value: '{{postgresUser}}'
        - name: POSTGRES_PASSWORD
          value: '{{postgresPassword}}'
        - name: POSTGRES_DB
          value: '{{postgresDb}}'
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      image: postgres:{{postgresTag}}
      volumeMounts:
        - name: data
          path: /var/lib/postgresql/data
  - name: tools
    container:
      endpoints:
        - exposure: public
          name: rails
          protocol: http
          targetPort: 5000
          path: /api
        - exposure: public
          name: webpack
          protocol: http
          targetPort: 3000
          path: /
      env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://localhost:6379/0
        - name: POSTGRES_USER
          value: '{{postgresUser}}'
        - name: POSTGRES_PASSWORD
          value: '{{postgresPassword}}'
        - name: POSTGRES_DB
          value: '{{postgresDb}}'
        - name: SKIP_TEST_DATABASE
          value: 'true'
      image: quay.io/ludovicus/rails-developer-image:bookwork-latest
      memoryLimit: 2G
      mountSources: true
  - name: data
    volume:
      size: 2Gi
  - name: cache
    volume:
      size: 1Gi
commands:
  - exec:
      commandLine: bundle install
      component: tools
      label: Ruby Dependencies
      workingDir: ${PROJECT_SOURCE}/scribe
    id: ruby-dependencies
  - exec:
      commandLine: npm install
      component: tools
      label: Nodejs Dependencies
      workingDir: ${PROJECT_SOURCE}/folio
    id: nodejs-dependencies
  - exec:
      commandLine: bundle exec bin/rails server
      component: tools
      env:
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: BIND
          value: 0.0.0.0
      group:
        kind: run
      label: Run application
      workingDir: ${PROJECT_SOURCE}/scribe
    id: run
  - exec:
      commandLine: bundle exec bin/rake db:drop
      component: tools
      group:
        kind: run
      label: Drop Database
      workingDir: ${PROJECT_SOURCE}/scribe
    id: drop-db
  - exec:
      commandLine: bundle exec bin/rake db:create
      component: tools
      group:
        kind: run
      label: Create Database
      workingDir: ${PROJECT_SOURCE}/scribe
    id: create-db
  - exec:
      commandLine: bundle exec bin/rake db:setup
      component: tools
      group:
        kind: run
      label: Setup Database
      workingDir: ${PROJECT_SOURCE}/scribe
    id: setup-db
  - exec:
      commandLine: bundle exec bin/rake db:migrate
      component: tools
      group:
        kind: run
      label: Migrate Database
      workingDir: ${PROJECT_SOURCE}/scribe
    id: migrate-db
variables:
  postgresDb: scroll
  postgresUser: scribe
  postgresPassword: as12349o8gjw8
  postgresTag: '16'
  redisTag: latest
